/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Client.gui;

import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;

import javax.swing.JOptionPane;

import Client.Client;
import System.Log;

/**
 *
 * @author fangyunniu
 */
public class CloudPanel extends javax.swing.JPanel {

	private static javax.swing.JFrame fileFrame;
	private static javax.swing.JFrame mainFrame;
	private Client client;
	private boolean needUpdate;
    /**
     * Creates new form CloudPanel
     */
    public CloudPanel(javax.swing.JFrame fileFrame
    		, javax.swing.JFrame mainFrame, Client client) {
    	this.fileFrame = fileFrame;
    	this.mainFrame = mainFrame;
    	this.client = client;
    
        initComponents();
        this.updateCloudFile();
    	this.needUpdate = false;
    }
    
    private void updateCloudFile() {
    	jComboBox1.removeAllItems();
    	// 初始化云端文件
        String filename = this.client.getFilename();
    	Log.println(filename);
    	
    	String[] filename_split = filename.trim().split("\\{");
    	for (int i = 0; i < filename_split.length; i ++) {
    		jComboBox1.addItem(filename_split[i]);
    	}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jSeparator3 = new javax.swing.JSeparator();
        downloadLabel = new javax.swing.JLabel();
        exitLabel = new javax.swing.JLabel();
        unloginLabel = new javax.swing.JLabel();
        updateLabel = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        FileLabel = new javax.swing.JLabel();
        pathTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(239, 241, 239));
        setPreferredSize(new java.awt.Dimension(540, 320));

        downloadLabel.setBackground(new java.awt.Color(101, 109, 138));
        downloadLabel.setFont(new java.awt.Font("幼圆", 1, 18)); // NOI18N
        downloadLabel.setForeground(new java.awt.Color(227, 234, 245));
        downloadLabel.setText("  下载");
        downloadLabel.setOpaque(true);
        downloadLabel.addMouseListener(new java.awt.event.MouseAdapter() {
        	public void mouseClicked(java.awt.event.MouseEvent evt) {
        		downloadMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                downloadLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                downloadLabelMouseExited(evt);
            }
        });

        exitLabel.setBackground(new java.awt.Color(101, 109, 138));
        exitLabel.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N
        exitLabel.setForeground(new java.awt.Color(227, 234, 245));
        exitLabel.setText("  退出");
        exitLabel.setOpaque(true);
        exitLabel.addMouseListener(new java.awt.event.MouseAdapter() {
        	public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitLabelMouseExited(evt);
            }
        });

        unloginLabel.setBackground(new java.awt.Color(101, 109, 138));
        unloginLabel.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N
        unloginLabel.setForeground(new java.awt.Color(227, 234, 245));
        unloginLabel.setText("  注销");
        unloginLabel.setOpaque(true);
        unloginLabel.addMouseListener(new java.awt.event.MouseAdapter() {
        	public void mouseClicked(java.awt.event.MouseEvent evt) {
        		unloginLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                unloginLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                unloginLabelMouseExited(evt);
            }
        });

        updateLabel.setBackground(new java.awt.Color(101, 109, 138));
        updateLabel.setFont(new java.awt.Font("幼圆", 1, 18)); // NOI18N
        updateLabel.setForeground(new java.awt.Color(227, 234, 245));
        updateLabel.setText("  上传");
        updateLabel.setOpaque(true);
        updateLabel.addMouseListener(new java.awt.event.MouseAdapter() {
        	public void mouseClicked(java.awt.event.MouseEvent evt) {
        		updateLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                updateLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                updateLabelMouseExited(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        FileLabel.setIcon(new javax.swing.ImageIcon(".\\graph\\File_25px.png")); // NOI18N
        FileLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FileLabelMouseClicked(evt);
            }
        });

        pathTextField.setBackground(new java.awt.Color(240, 240, 240));
        pathTextField.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        pathTextField.setBorder(null);
        pathTextField.setEditable(false);
        pathTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pathTextFieldActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("华文彩云", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setIcon(new javax.swing.ImageIcon(".\\graph\\choosefile.png")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(unloginLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79)
                        .addComponent(exitLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 100, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(FileLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pathTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(downloadLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(FileLabel)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(pathTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(updateLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(downloadLabel))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exitLabel)
                    .addComponent(unloginLabel))
                .addGap(34, 34, 34))
        );
    }// </editor-fold>                        
    protected void downloadMouseClicked(MouseEvent evt) {
		// TODO Auto-generated method stub
    	Log.println("选择了第 " + jComboBox1.getSelectedIndex()
    				+ "个文件");
    	String path = new DownloadChooser().getSelected();
    	if (path.equals("")) {
			JOptionPane.showMessageDialog(null, "请选择一个下载路径！");
		} else {
			String res = client.downloadFile(path, jComboBox1.getSelectedIndex());
			if (!res.startsWith("download now")) {
				JOptionPane.showMessageDialog(null, "下载失败！");
			}
		}
	}

	protected void jComboBox1MouseClicked(MouseEvent evt) {
		// TODO Auto-generated method stub
    	if (needUpdate) {
    		pathTextField.setText("");
    		this.updateCloudFile();
    		this.needUpdate = false;
    	}
	}

	protected void updateLabelMouseClicked(MouseEvent evt) {
		// TODO Auto-generated method stub
		if (pathTextField.getText().equals("")) {
			JOptionPane.showMessageDialog(null, "请至少选择一个文件！");
		} else {
			String res = client.updateFile(pathTextField.getText());
			if (!res.startsWith("send successfully: ")) {
				JOptionPane.showMessageDialog(null, "传输失败！");
			}
			this.needUpdate = true;
		}
	}

	protected void exitLabelMouseClicked(MouseEvent evt) {
		// TODO Auto-generated method stub
    	int n = JOptionPane.showConfirmDialog(null, "确认退出?", "提示", JOptionPane.YES_NO_OPTION);   
    	if (n == JOptionPane.YES_OPTION) {   
    		if (client.closeAPPSSocket()) {
	    		Log.println("注销成功！");
    		} else {
    			Log.println("注销失败！");
    		}
    		System.exit(0);
    	}
	}

	protected void unloginLabelMouseClicked(MouseEvent evt) {
		// TODO Auto-generated method stub
    	int n = JOptionPane.showConfirmDialog(null, "确认注销?", "提示", JOptionPane.YES_NO_OPTION);   
    	if (n == JOptionPane.YES_OPTION) {   
    		if (client.closeAPPSSocket()) {
	    		JOptionPane.showMessageDialog(null, "注销成功！");
    		} else {
    			JOptionPane.showMessageDialog(null,  "注销失败，请重新登录！"
    					, "出错啦", JOptionPane.ERROR_MESSAGE);
    		}
    		this.fileFrame.setVisible(false);
    		this.mainFrame.setVisible(true);
    		this.fileFrame.dispose();
    	}
	}

	private void downloadLabelMouseEntered(java.awt.event.MouseEvent evt) {                                           
        // TODO add your handling code here:
        downloadLabel.setForeground(new java.awt.Color(105, 114, 145));
        downloadLabel.setBackground(new java.awt.Color(222, 221, 222));
        
    }                                          

    private void downloadLabelMouseExited(java.awt.event.MouseEvent evt) {                                          
        // TODO add your handling code here:
        downloadLabel.setForeground(new java.awt.Color(227, 234, 245));
        downloadLabel.setBackground(new java.awt.Color(101,109,138));
    }                                         

    private void exitLabelMouseEntered(java.awt.event.MouseEvent evt) {                                       
        // TODO add your handling code here:
        exitLabel.setForeground(new java.awt.Color(105, 114, 145));
        exitLabel.setBackground(new java.awt.Color(222, 221, 222));
    }                                      

    private void exitLabelMouseExited(java.awt.event.MouseEvent evt) {                                      
        // TODO add your handling code here:
        exitLabel.setForeground(new java.awt.Color(227, 234, 245));
        exitLabel.setBackground(new java.awt.Color(101,109,138));
    }                                     

    private void unloginLabelMouseEntered(java.awt.event.MouseEvent evt) {                                          
        // TODO add your handling code here:
        unloginLabel.setForeground(new java.awt.Color(105, 114, 145));
        unloginLabel.setBackground(new java.awt.Color(222, 221, 222));
    }                                         

    private void unloginLabelMouseExited(java.awt.event.MouseEvent evt) {                                         
        // TODO add your handling code here:
        unloginLabel.setForeground(new java.awt.Color(227, 234, 245));
        unloginLabel.setBackground(new java.awt.Color(101,109,138));
    }                                        

    private void updateLabelMouseEntered(java.awt.event.MouseEvent evt) {                                         
        // TODO add your handling code here:
        updateLabel.setForeground(new java.awt.Color(105, 114, 145));
        updateLabel.setBackground(new java.awt.Color(222, 221, 222));
    }                                        

    private void updateLabelMouseExited(java.awt.event.MouseEvent evt) {                                        
        // TODO add your handling code here:
        updateLabel.setForeground(new java.awt.Color(227, 234, 245));
        updateLabel.setBackground(new java.awt.Color(101,109,138));
    }                                       

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void FileLabelMouseClicked(java.awt.event.MouseEvent evt) {                                       
        // TODO add your handling code here:
        pathTextField.setText(new FileChooser().getSelected()/*.replaceAll("\\", "\\\\")*/);
    }                                      

    private void pathTextFieldActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             


    // Variables declaration - do not modify                     
    private javax.swing.JLabel FileLabel;
    private javax.swing.JLabel downloadLabel;
    private javax.swing.JLabel exitLabel;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField pathTextField;
    private javax.swing.JLabel unloginLabel;
    private javax.swing.JLabel updateLabel;
    // End of variables declaration                   
}
