/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Client.gui;

import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;

import Client.Client;
import System.Log;

/**
 *
 * @author fangyunniu
 */
public class FileFrame extends javax.swing.JFrame {

    
    /**
     *  用于解决窗体拖动问题
     */
    private static Point origin = new Point();
    private static javax.swing.JFrame thisFrame;
    private boolean isOpen1;
    private boolean isOpen2;
    private boolean isOpen3;
    
    private static javax.swing.JFrame mainFrame;
    private Client client;
    
    /**
     * Creates new form NewJFrame
     */
    public FileFrame(javax.swing.JFrame mainFrame, Client client) {
        
    	this.client = client;
    	this.mainFrame = mainFrame;
    	this.client.setFileFrame(this);
    
        initComponents();
         /**
         *  居中并使得窗口可以拖动
         * @author NiuYunfang
         */
        thisFrame = this;
        setLocationRelativeTo(null);
        thisFrame.addMouseListener(new MouseAdapter(){
            //按下(mousePressed不是点击，而是鼠标被按下没有抬起)
            @Override
            public void mousePressed(MouseEvent e){
                //当鼠标按下的时候获得窗口当前的位置
                origin.x = e.getX();
                origin.y = e.getY();
            }
         });     
        thisFrame.addMouseMotionListener(new MouseMotionAdapter(){
            //拖动(mouseDragged指的不是鼠标在窗口中移动，而是用鼠标拖动)
            @Override
            public void mouseDragged(MouseEvent e){
                //当鼠标拖动时获取窗口当前位置
                Point p = thisFrame.getLocation();
                //设置窗口的位置
                //窗口当前的位置+鼠标当前在窗口的位置 - 鼠标按下的时候在窗口的位置
                thisFrame.setLocation(p.x + e.getX() - origin.x, p.y + e.getY()- origin.y);
            }
        });
        
        isOpen3 = false;
        
        isOpen2 = true;
        jLabel2.setBackground(new java.awt.Color(240, 240, 240));
        jLabel2.setForeground(new java.awt.Color(105, 114, 145));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        OpeningPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout OpeningPanelLayout = new javax.swing.GroupLayout(OpeningPanel);
        OpeningPanel.setLayout(OpeningPanelLayout);
        OpeningPanelLayout.setHorizontalGroup(
            OpeningPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );
        OpeningPanelLayout.setVerticalGroup(
            OpeningPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );

        OpeningPanel = new CloudPanel(this, this.mainFrame, client);

        getContentPane().add(OpeningPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 540, 320));

        jLabel2.setBackground(new java.awt.Color(101, 109, 138));
        jLabel2.setFont(new java.awt.Font("幼圆", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(227, 234, 245));
        jLabel2.setText("           云端文件");
        jLabel2.setOpaque(true);
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 30));

        jLabel3.setBackground(new java.awt.Color(101, 109, 138));
        jLabel3.setFont(new java.awt.Font("幼圆", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(227, 234, 245));
        jLabel3.setText("            传送文件");
        jLabel3.setOpaque(true);
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 270, 30));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setEditable(false);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 540, 110));

        pack();
    }// </editor-fold>                              

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {                                     
        // TODO add your handling code here:
        if (!isOpen2) {
            closePanel();
            OpenPanel(new CloudPanel(this, this.mainFrame, this.client));
            isOpen2 = true;
            jLabel2.setBackground(new java.awt.Color(240, 240, 240));
        }
    }                                    

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {                                     
        // TODO add your handling code here:
        if (!isOpen2) {
            jLabel2.setForeground(new java.awt.Color(105, 114, 145));
            jLabel2.setBackground(new java.awt.Color(222, 221, 222));
        }
    }                                    

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {                                    
        // TODO add your handling code here:
        if (!isOpen2) {
            jLabel2.setForeground(new java.awt.Color(227, 234, 245));
            jLabel2.setBackground(new java.awt.Color(101,109,138));
        }
    }                                   

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {                                     
        // TODO add your handling code here:
        if (!isOpen3) {
            closePanel();
            OpenPanel(new TransferPanel(this.client));
            isOpen3 = true;
            jLabel3.setBackground(new java.awt.Color(240, 240, 240));
        }
    }                                    

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {                                     
        // TODO add your handling code here:
        if (!isOpen3) {
            jLabel3.setForeground(new java.awt.Color(105, 114, 145));
            jLabel3.setBackground(new java.awt.Color(222, 221, 222));
        }
    }                                    

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {                                    
        // TODO add your handling code here:
        if (!isOpen3) {
            jLabel3.setForeground(new java.awt.Color(227, 234, 245));
            jLabel3.setBackground(new java.awt.Color(101,109,138));
        }
    }                                   

    private void OpenPanel(javax.swing.JPanel p) {

        OpeningPanel = p;
        OpeningPanel.setVisible(true);
        getContentPane().add(OpeningPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 540, 320));
        //p.setVisible(true);
        
    }
    
    private void closePanel() {
        
        OpeningPanel.setVisible(false);
        if (isOpen2) {
            isOpen2 = false;
            jLabel2.setBackground(new java.awt.Color(101,109,138));
            jLabel2.setForeground(new java.awt.Color(227, 234, 245));
        } else if (isOpen3) {
            isOpen3 = false;
            jLabel3.setBackground(new java.awt.Color(101,109,138));
            jLabel3.setForeground(new java.awt.Color(227, 234, 245));
        }
    }
    
    public void append(String text) {
    	
    	jTextArea1.append(text + "\n\n");
    	jTextArea1.setCaretPosition(jTextArea1.getDocument().getLength());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FileFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FileFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FileFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FileFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              //  new FileFrame(new MainFrame().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify                     
    private javax.swing.JPanel OpeningPanel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration                     
}
