/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Client.gui;

import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import java.io.FileNotFoundException;

import javax.swing.JOptionPane;

import Client.Client;
import System.FileHandle;
import System.IpAdd;
import System.Log;

/**
 *
 * @author fangyunniu
 */
public class SettingsPanel extends javax.swing.JPanel {

    private static Client client;
	/**
     * Creates new form SettingsPanel
     */
    public SettingsPanel(Client client) {
    	
    	this.client = client;
        initComponents();
        
        jTextFieldAS.setText(client.getAS());
        jTextFieldTGS.setText(client.getTGS());
        jTextFieldAPPS.setText(client.getAPPS());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldAPPS = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldTGS = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldAS = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(241, 239, 241));

        jLabel1.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N
        jLabel1.setText("服务器");

        jLabel2.setFont(new java.awt.Font("华文彩云", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("输入IP地址");

        jTextFieldAPPS.setBackground(new java.awt.Color(240, 240, 240));
        jTextFieldAPPS.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jTextFieldAPPS.setBorder(null);
        jTextFieldAPPS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        jTextFieldAPPS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N
        jLabel3.setText("TGS");

        jLabel7.setBackground(new java.awt.Color(101, 109, 138));
        jLabel7.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(227, 234, 245));
        jLabel7.setText("  完成");
        jLabel7.setOpaque(true);
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel7MouseExited(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        jTextFieldTGS.setBackground(new java.awt.Color(240, 240, 240));
        jTextFieldTGS.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jTextFieldTGS.setBorder(null);
        jTextFieldTGS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N
        jLabel4.setText("AS");

        jTextFieldAS.setBackground(new java.awt.Color(240, 240, 240));
        jTextFieldAS.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jTextFieldAS.setBorder(null);
        jTextFieldAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField2ActionPerformed(evt);
            }
        });
        jTextFieldAS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField2KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPasswordField2KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator1)
                            .addComponent(jTextFieldTGS)
                            .addComponent(jSeparator2)
                            .addComponent(jTextFieldAPPS, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator3)
                            .addComponent(jTextFieldAS, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(131, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(214, 214, 214))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(171, 171, 171))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jTextFieldAS, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldTGS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jTextFieldAPPS, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addGap(27, 27, 27)
                .addComponent(jLabel7)
                .addGap(38, 38, 38))
        );
    }// </editor-fold>                        

    protected void jLabel7MouseClicked(MouseEvent evt) {
    	// 判断输入的是否为合法IP
		// TODO Auto-generated method stub
		if ((IpAdd.isIP(jTextFieldAS.getText()))
		 && (IpAdd.isIP(jTextFieldTGS.getText()))
		 && (IpAdd.isIP(jTextFieldAPPS.getText()))) {
			String AS_IP = jTextFieldAS.getText();
 			String TGS_IP = jTextFieldTGS.getText();
 			String APPS_IP = jTextFieldAPPS.getText();
 			client.setAS(AS_IP);
 			client.setTGS(TGS_IP);
 			client.setAPP(APPS_IP);
 			try {
				FileHandle.creat("./host.txt", AS_IP + " " + TGS_IP + " " + APPS_IP);
			} catch (FileNotFoundException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
			JOptionPane.showMessageDialog(null, "设置成功！");
		} else {
			JOptionPane.showMessageDialog(null,  "IP地址不合法！", "出错啦", JOptionPane.ERROR_MESSAGE);
		}
	}

	private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
    }                                               

    private void jPasswordField1KeyPressed(java.awt.event.KeyEvent evt) {                                           
        // TODO add your handling code here:
        if(evt.getKeyChar() == KeyEvent.VK_ENTER ) {
            jLabel7.setForeground(new java.awt.Color(105, 114, 145));
            jLabel7.setBackground(new java.awt.Color(222, 221, 222));
            // 判断输入的是否为合法IP
         	// TODO Auto-generated method stub
     		if ((IpAdd.isIP(jTextFieldAS.getText()))
     		 && (IpAdd.isIP(jTextFieldTGS.getText()))
     		 && (IpAdd.isIP(jTextFieldAPPS.getText()))) {
     			
     			String AS_IP = jTextFieldAS.getText();
     			String TGS_IP = jTextFieldTGS.getText();
     			String APPS_IP = jTextFieldAPPS.getText();
     			client.setAS(AS_IP);
     			client.setTGS(TGS_IP);
     			client.setAPP(APPS_IP);
     			try {
					FileHandle.creat("./host.txt", AS_IP + " " + TGS_IP + " " + APPS_IP);
				} catch (FileNotFoundException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
     			JOptionPane.showMessageDialog(null, "设置成功！");
     		} else {
     			JOptionPane.showMessageDialog(null,  "IP地址不合法！", "出错啦", JOptionPane.ERROR_MESSAGE);
     		}
        }
    }                                          

    private void jPasswordField1KeyReleased(java.awt.event.KeyEvent evt) {                                            
        // TODO add your handling code here:
        if(evt.getKeyChar() == KeyEvent.VK_ENTER ) {
            jLabel7.setForeground(new java.awt.Color(227, 234, 245));
            jLabel7.setBackground(new java.awt.Color(101,109,138));
        }
    }                                           

    private void jLabel7MouseEntered(java.awt.event.MouseEvent evt) {                                     
        // TODO add your handling code here:
        jLabel7.setForeground(new java.awt.Color(105, 114, 145));
        jLabel7.setBackground(new java.awt.Color(222, 221, 222));
    }                                    

    private void jLabel7MouseExited(java.awt.event.MouseEvent evt) {                                    
        // TODO add your handling code here:
        jLabel7.setForeground(new java.awt.Color(227, 234, 245));
        jLabel7.setBackground(new java.awt.Color(101,109,138));
    }                                   

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void jPasswordField2ActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
    }                                               

    private void jPasswordField2KeyPressed(java.awt.event.KeyEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void jPasswordField2KeyReleased(java.awt.event.KeyEvent evt) {                                            
        // TODO add your handling code here:
    }                                           


    // Variables declaration - do not modify                     
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextFieldAPPS;
    private javax.swing.JTextField jTextFieldAS;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTextFieldTGS;
    // End of variables declaration                   
}
