/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Client.gui;

import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;

import javax.swing.JOptionPane;

import Client.Client;
import System.Log;

/**
 *
 * @author fangyunniu
 */
public class TransferPanel extends javax.swing.JPanel {
	
	private Client client;
    /**
     * Creates new form CloudPanel
     */
    public TransferPanel(Client client) {
    	
    	this.client = client;
        initComponents();
        this.updateCntusr();
    }
    
    private void updateCntusr() {
    	jComboBox1.removeAllItems();
    	// 初始化云端文件
        String filename = this.client.getCntusr();
    	Log.println(filename);
    	
    	String[] filename_split = filename.trim().split(" ");
    	for (int i = 0; i < filename_split.length; i ++) {
    		jComboBox1.addItem(filename_split[i]);
    	}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jSeparator3 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        transferLabel = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        FileLabel = new javax.swing.JLabel();
        pathTextField = new javax.swing.JTextField();

        setBackground(new java.awt.Color(239, 241, 239));

        jLabel2.setFont(new java.awt.Font("华文彩云", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setIcon(new javax.swing.ImageIcon(".\\graph\\choosefile.png")); // NOI18N

        transferLabel.setBackground(new java.awt.Color(101, 109, 138));
        transferLabel.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N
        transferLabel.setForeground(new java.awt.Color(227, 234, 245));
        transferLabel.setText("  发送");
        transferLabel.setOpaque(true);
        transferLabel.addMouseListener(new java.awt.event.MouseAdapter() {
        	public void mouseClicked(java.awt.event.MouseEvent evt) {
                transferLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                transferLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                transferLabelMouseExited(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        FileLabel.setIcon(new javax.swing.ImageIcon(".\\graph\\File_25px.png")); // NOI18N
        FileLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FileLabelMouseClicked(evt);
            }
        });

        pathTextField.setBackground(new java.awt.Color(240, 240, 240));
        pathTextField.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        pathTextField.setBorder(null);
        pathTextField.setEditable(false);
        pathTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pathTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(transferLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(FileLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pathTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(137, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(FileLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pathTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(42, 42, 42)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(transferLabel)
                .addGap(32, 32, 32))
        );
    }// </editor-fold>                        

    protected void transferLabelMouseClicked(MouseEvent evt) {
		// TODO Auto-generated method stub  	
    	String usr = (String) jComboBox1.getSelectedItem();
    	Log.println("你选择了: " + usr);
    	if (usr.equals("")) {
			JOptionPane.showMessageDialog(null, "请选择发送对象！");
		}
    	else if (pathTextField.getText().equals("")) {
			JOptionPane.showMessageDialog(null, "请选择发送文件！");
		} else {
			this.client.setWaitTransferFile(pathTextField.getText());
			this.client.sendFileToClient(Short.parseShort(usr));
		}
    	this.updateCntusr();
	}

	private void transferLabelMouseEntered(java.awt.event.MouseEvent evt) {                                           
        // TODO add your handling code here:
        transferLabel.setForeground(new java.awt.Color(105, 114, 145));
        transferLabel.setBackground(new java.awt.Color(222, 221, 222));
    }                                          

    private void transferLabelMouseExited(java.awt.event.MouseEvent evt) {                                          
        // TODO add your handling code here:
        transferLabel.setForeground(new java.awt.Color(227, 234, 245));
        transferLabel.setBackground(new java.awt.Color(101,109,138));
    }                                         

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void FileLabelMouseClicked(java.awt.event.MouseEvent evt) {                                       
        // TODO add your handling code here:
        pathTextField.setText(new FileChooser().getSelected());
    }                                      

    private void pathTextFieldActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                  


    // Variables declaration - do not modify                     
    private javax.swing.JLabel FileLabel;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField pathTextField;
    private javax.swing.JLabel transferLabel;
    // End of variables declaration                   
}
